name: Profile Metrics Generator

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"
  # Or manually trigger workflow
  workflow_dispatch:

jobs:
  generate-github-metrics:
    name: GitHub Metrics and Design Portfolio Update
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Basic metrics
      - name: Basic Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          config_timezone: Asia/Kolkata
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_details: bytes-percentage, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          
      # Pinned repositories for design projects
      - name: Pinned Projects
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: your-featured-design-repo
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_limit: 4
          
      # Design related activities
      - name: Activity Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: B      
          
      # Design social media from Behance and Dribbble
      - name: Design Social Media
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.social.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_user: your-twitter-username
          plugin_tweets_limit: 2
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: your-stackoverflow-id
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_limit: 2 